### ISSUE TITLE
Source does not support feature count

### ISSUE THREAD

**Issue by bholtdwyer** [openaddresses/pyesridump#75]
Hi! I'm not sure if this is an error or just a problem the code can't yet surmount. I try the following:

`(esridump) holtdwyer@CuChulainn ~/Documents/res/teevrat/get_esri % esri2geojson http://gis-gfw.wri.org/arcgis/rest/services/commodities/MapServer/12 indonesia_landcover.geojson
2021-07-13 19:38:36,369 - cli.esridump - INFO - Source does not support feature count
Traceback (most recent call last):
  File "/Users/holtdwyer/Documents/res/teevrat/get_esri/esridump/bin/esri2geojson", line 8, in <module>
    sys.exit(main())
  File "/Users/holtdwyer/Documents/res/teevrat/get_esri/esridump/lib/python3.9/site-packages/esridump/cli.py", line 114, in main
    feature = next(feature_iter)
  File "/Users/holtdwyer/Documents/res/teevrat/get_esri/esridump/lib/python3.9/site-packages/esridump/dumper.py", line 343, in __iter__
    oid_field_name = self._find_oid_field_name(metadata)
  File "/Users/holtdwyer/Documents/res/teevrat/get_esri/esridump/lib/python3.9/site-packages/esridump/dumper.py", line 167, in _find_oid_field_name
    for f in metadata['fields']:
TypeError: 'NoneType' object is not iterable`

Apparently, the server is returning something that isn't iterable when asked for an enterable feature list. Is there any way to get the pull to work regardless?

**Comment by iandees** [comment]
It looks like this layer you're pulling from doesn't have any fields, so it can't find the OID field name to do one of the feature extraction steps.

We can fix this so that it would skip over this option and not give an error, but I don't think it would be able to extract data from this layer because of a server side configuration problem. You can try to query the layer yourself by [querying for `1=1`](http://gis-gfw.wri.org/arcgis/rest/services/commodities/MapServer/12/query?where=1%3D1&text=&objectIds=&time=&geometry=&geometryType=esriGeometryEnvelope&inSR=&spatialRel=esriSpatialRelIntersects&relationParam=&outFields=&returnGeometry=true&returnTrueCurves=false&maxAllowableOffset=&geometryPrecision=&outSR=&having=&returnIdsOnly=false&returnCountOnly=false&orderByFields=&groupByFieldsForStatistics=&outStatistics=&returnZ=false&returnM=false&gdbVersion=&historicMoment=&returnDistinctValues=false&resultOffset=&resultRecordCount=&queryByDistance=&returnExtentOnly=false&datumTransformation=&parameterValues=&rangeValues=&quantizationParameters=&f=html) and you get an error.

**Comment by iandees** [comment]
There are no features to extract from that layer of the MapServer because it's a raster layer. You can see the pixels [on this sample page](https://www.arcgis.com/home/webmap/viewer.html?url=http%3A%2F%2Fgis-gfw.wri.org%2Farcgis%2Frest%2Fservices%2Fcommodities%2FMapServer&source=sd) if you zoom in and select just the "Landcover - Southeast Asia" layer.

**Comment by Geremia** [comment]
@iandees I get "INFO - Source does not support feature count" with [this map](https://gis.mcassessor.maricopa.gov/arcgis/rest/services/Parcels/MapServer/0), and I'm able to run [a `1=1` query on it](https://gis.mcassessor.maricopa.gov/arcgis/rest/services/Parcels/MapServer/0/query?where=1%3D1&text=&objectIds=&time=&geometry=&geometryType=esriGeometryEnvelope&inSR=&spatialRel=esriSpatialRelIntersects&relationParam=&outFields=&returnGeometry=true&returnTrueCurves=false&maxAllowableOffset=&geometryPrecision=&outSR=&having=&returnIdsOnly=false&returnCountOnly=false&orderByFields=&groupByFieldsForStatistics=&outStatistics=&returnZ=false&returnM=false&gdbVersion=&historicMoment=&returnDistinctValues=false&resultOffset=&resultRecordCount=&queryByDistance=&returnExtentOnly=false&datumTransformation=&parameterValues=&rangeValues=&quantizationParameters=&f=html) successfully.
